import { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { BarChart3, Code2, PenTool, FileText, GitBranch, MessageCircle, Send, Sparkles, Users, X } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { WORKSPACES, MESSAGES } from '../mock/data';
import { PROBLEMS } from '../mock/problems';

const TOOLS = [{ id: 'code', name: 'Code Studio', detail: 'Shared implementation workspace', icon: Code2, color: '#2878f0' }, { id: 'design', name: 'Design Board', detail: 'Flows, screens, and feedback', icon: PenTool, color: '#f24e1e' }, { id: 'repo', name: 'Repository', detail: 'Branches, pull requests, and files', icon: GitBranch, color: '#24292f' }, { id: 'data', name: 'Insights', detail: 'Research and project metrics', icon: BarChart3, color: '#13a078' }];

export default function Workspace() {
  const { id } = useParams(); const navigate = useNavigate(); const { user } = useAuth(); const [messages, setMessages] = useState([]); const [text, setText] = useState(''); const [tool, setTool] = useState(null); const bottomRef = useRef();
  const mine = WORKSPACES.filter(ws => ws.members.some(member => member.id === user?.id)); const workspace = WORKSPACES.find(ws => ws.id === Number(id)); const problem = workspace?.problem_id ? PROBLEMS.find(item => item.id === workspace.problem_id) : null;
  useEffect(() => { if (!id && mine[0]) navigate(`/workspace/${mine[0].id}`, { replace: true }); }, [id, mine, navigate]);
  useEffect(() => { if (workspace) setMessages(MESSAGES[workspace.id] || []); }, [workspace?.id]);
  useEffect(() => { bottomRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages]);
  if (!user || (!id && mine.length)) return null;
  if (!workspace) return <div className="ws-loading">Workspace not found</div>;
  const send = event => { event.preventDefault(); if (!text.trim()) return; setMessages(previous => [...previous, { _id: `m${Date.now()}`, senderId: user.id, senderName: user.name, senderAvatar: user.avatar, text: text.trim() }]); setText(''); };
  const ToolIcon = tool?.icon;
  return <main className="collab-page"><header className="collab-hero"><div><span className="collab-label">ACTIVE COLLABORATION</span><h1>{problem?.title || workspace.name}</h1><p>{problem?.description || 'A shared project space for the team to plan, create, and deliver their solution.'}</p><div className="collab-meta"><span><FileText size={14} /> {problem?.category || 'Challenge project'}</span><span><Users size={14} /> {workspace.members.length} collaborators</span></div></div><div className="collab-people">{workspace.members.map(member => <div key={member.id} title={member.name}>{member.avatar ? <img src={member.avatar} alt="" /> : member.name[0]}</div>)}</div></header><section className="collab-tools"><div className="collab-section-head"><div><Sparkles size={16} /><b>Project tools</b></div><span>Open a collaborative mock workspace</span></div><div className="collab-tool-grid">{TOOLS.map(item => { const Icon = item.icon; return <button key={item.id} onClick={() => setTool(item)} className="collab-tool"><i style={{ background: `${item.color}18`, color: item.color }}><Icon size={20} /></i><span><b>{item.name}</b><small>{item.detail}</small></span></button>; })}</div></section><section className="collab-chat"><div className="collab-section-head"><div><MessageCircle size={16} /><b>Team discussion</b></div><span>Live mock chat</span></div><div className="collab-messages">{messages.map(message => { const isMine = message.senderId === user.id; return <div className={`collab-message ${isMine ? 'mine' : ''}`} key={message._id}><div className="collab-avatar">{message.senderAvatar ? <img src={message.senderAvatar} alt="" /> : message.senderName?.[0]}</div><div><b>{isMine ? 'You' : message.senderName}</b><p>{message.text}</p></div></div>; })}<div ref={bottomRef} /></div><form className="collab-compose" onSubmit={send}><input value={text} onChange={event => setText(event.target.value)} placeholder="Share an update with the team" /><button type="submit" disabled={!text.trim()}><Send size={16} /></button></form></section>{tool && <div className="tool-overlay" onClick={() => setTool(null)}><section className="tool-window" onClick={event => event.stopPropagation()}><header><div><i style={{ color: tool.color }}><ToolIcon size={19} /></i><div><b>{tool.name}</b><span>{tool.detail} · Team workspace</span></div></div><button onClick={() => setTool(null)}><X size={19} /></button></header><div className={`tool-canvas ${tool.id}`}><b>{tool.id === 'code' ? 'src / solution.js' : tool.id === 'design' ? 'Reporting flow — shared canvas' : tool.id === 'repo' ? 'main · 2 pull requests ready' : 'Research insights updated today'}</b><p>This is an interactive mock view for your team’s {tool.name.toLowerCase()}.</p><div /><div /><div /></div><footer><Users size={15} /> {workspace.members.length} teammates are collaborating in this mock tool</footer></section></div>}</main>;
}
